### ISSUE TITLE
User model checkPassword as callback

### ISSUE THREAD

**Issue by ksmithut** [t1msh/node-oauth20-provider#13]
I'm loving this library, but there's only one thing that's stopping me from implementing it. I have user passwords hashed using the [`bcrypt`](https://www.npmjs.com/package/bcrypt) library. It hashes passwords for me, but it's asynchronous, so I can't use the checkPassword method.

**Comment by t1msh** [comment]
First of all thank you!
I added possibility to check password via callback method to handle both async/sync styles. 
But anyway you could do this via sync method too (even with bcrypt library). Everyone is talking about "never ever write sync code in nodejs" but simple password check is not that place to avoid it, you can implement it any style (assuming password is short enough)

**Comment by ksmithut** [comment]
Thanks :) I believe that having it hash synchronously would make it a
dangerous attack vector, but if some is going to attack you in that way,
there are much better ways to prevent it.
