### ISSUE TITLE
Access Token revocation

### ISSUE THREAD

**Issue by emanuelef** [t1msh/node-oauth20-provider#14]
Hi,
this is more a question on revocation.
How can the Authorization Server revoke a valid Access Token ?
In my use case I have a third party app using Client Credentials Flow, what if at some point I find the app is malicious and I want to revoke its access?
Thanks

**Comment by t1msh** [comment]
Hi
Usually access tokens are not revoked at all, they have limited life time (some hours for example) but of course one can implement that logic if it is vital. 
Common practice: if you need to revoke access you should delete refresh tokens issued to this app (so malicious app has no option to acquire/refresh access token). 
PS Also it is a good practice to delete refresh tokens on user password change event.

**Comment by emanuelef** [comment]
Thanks a lot for the quick reply.
I couldn't find an example in your library to perform a POST for revocation, is that supported by the library?
Or maybe I'm wrong and it shouldn't be part of the library but in my business logic.

The use case is: a third party client app registers and gets clientId/ClientSecret, then uses Client Credentials flow to get Access Token and then perform APIs calls on the Resource Server.
I then decide to revoke the access to my APIs to that particular client App, if the Authorization server doesn't revoke the Access Token (and even the Refresh one) the client can keep performing secured APIs calls.
I could just revoke the Refresh Token and wait the Access Token to expire, is this something tha can be done using the OAuth library?

I see Twitter has https://api.twitter.com/oauth2/invalidate_token

Thanks again for any tips on that.

**Comment by t1msh** [comment]
Oh sorry
I replied a bit in a wrong way
If client is malicious - you should delete all (or block) info related to it (refresh tokens, client info -clientId, clientSecret, etc). So this client should have no option to get new access tokens related to all the users
If some user data leaked 9refresh tokens) and someone is using user info in a harmful way - you should delete all refresh tokens related to that user (as well if user changes password)
Client, user, refresh token, access token management - are out of the scope of the library, one should implement it in any way. You should have some kind of admin panel to do it (delete/block/approve and etc) as well application should have user registration and client registration. Library just provides mechanics to authorize user and does not force any kind of management implementation. 
Short answer - there is no request to do it

**Comment by emanuelef** [comment]
So should I do something like this:

- store a black list of tokens, clientIds, clientSecrets (in a DB I manage)
- when a new API call is performed check if it's from one black listed token or client by inspecting query parameters or Authorization header (manually without the use of the OAuth library ?)
- prevent access if in the black list

I guess that in that case the Oauth layer could even not know that a revocation has occurred, it's just my business logic to handle this.
Am I right ?
Because I was thinking that if a revocation has happened the Oauth library should be informed in some way.

Thanks again

**Comment by t1msh** [comment]
Black list case
All you need is to add black list check to redefined "client.fetchById" function. This function receives "clientId" parameter and returns "client" object if it is found. If client is not found (or found but client is black listed) - just return empty callback. This function is async so you can implement any logic (ask different DB, cache layers and etc) to get black lists or smth. (ofc the most common thing to do is to store "block" state in client object)
OAuth layer does not (and should not) know if revocation happened, all it should do is - grant or do not grant access.

**Comment by emanuelef** [comment]
Thanks for the detailed answer.

**Comment by djmadcat** [comment]
[OAuth 2.0 Token Revocation](https://tools.ietf.org/html/rfc7009)
