### ISSUE TITLE
Change 8b3db5b for #13 broke semantic versioning of module

### ISSUE THREAD

**Issue by stemail23** [t1msh/node-oauth20-provider#16]
Change 8b3db5b introduced a change that broke existing code. By changing the signature of checkPassword to callback, rather than return values, ALL existing implementations using this library would have broken (including mine!)

The library should have been updated to 0.4.0, not 0.3.5!

To maintain backwards compatibility, the implementation should have returned the checked password response if the callback was not provided.

**Comment by t1msh** [comment]
Yes, i know that. I've missed it and corrected version too late. Should i unpublish 0.3.5 from the registry? or just deprecate it?

**Comment by stemail23** [comment]
Cool. Didn't notice you'd published 0.4. Agree that deprecating 0.3.5 seems like the correct option, although not sure what that does if anybody has non snapshotted it?

Cheers for the library btw, appreciate the effort!

**Comment by stemail23** [comment]
non = npm (autocorrect!)

**Comment by t1msh** [comment]
Done. Thank you for your feedback
