### ISSUE TITLE
Token generation and save

### ISSUE THREAD

**Issue by conet** [t1msh/node-oauth20-provider#17]
Hi,

I'm not sure that an issue should be opened for this but it's the only place I found that I can describe a problem that I have with this library, which is really nice, by the way.

I feel that the way tokens can be saved is limited because of the way the controller interacts with the (access|refresh)Token models.

Because token generation (generateToken) is separated from token serialization (save), a serialization method which affects the token's representation (like a JWT) can't be used.

Each call to generateToken is followed by a save, I feel that changing this interaction with a single call to a *create* function just like *save* without the first parameter, which returns an error or a token which would be then used would support both current serialization method and the one I would like to use.

Something along the lines of:
**Original**
```
        // Generate new accessToken and save it
        function(cb) {
            accessTokenValue = oauth2.model.accessToken.generateToken();
            oauth2.model.accessToken.save(accessTokenValue, oauth2.model.code.getUserId(code), oauth2.model.code.getClientId(code), oauth2.model.code.getScope(code), oauth2.model.accessToken.ttl, function(err) {
                if (err)
                    cb(new error.serverError('Failed to call accessToken::save method'));
                else {
                    oauth2.logger.debug('Access token saved: ', accessTokenValue);
                    cb();
                }
            });
        },
```
**Improved version**
```
        // Generate new accessToken
        function(cb) {
            oauth2.model.accessToken.create(accessTokenValue, oauth2.model.code.getUserId(code), oauth2.model.code.getClientId(code), oauth2.model.code.getScope(code), oauth2.model.accessToken.ttl, function(err, token) {
                if (err)
                    cb(new error.serverError('Failed to call accessToken::save method'));
                else {
                    accessTokenValue = token;
                    oauth2.logger.debug('Access token saved: ', accessTokenValue);
                    cb();
                }
            });
        },
```

What do you think?

**Comment by t1msh** [comment]
Hi, ty for your feedback
I see nothing wrong here, i'll couple this functions asap
